import styles from './page.module.css';
export const metadata = {
  title: "My Home Page",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <div className={styles.container}>
      <h2>Hello from Next.js</h2>
      <p>Hello from Martin</p>
    </div>
  );
}