export const metadata = {
    title: "Student Information",
    description: "Generated by create next app",
  };
const Students = () =>{
    return (
        <div>
            <h2>Information for Students</h2>
        </div>
    );
}
export default Students;