export const metadata = {
    title: "Staff Information",
    description: "Generated by create next app",
  };
const Staff = () =>{
    return (
        <div>
            <h2>Staff</h2>
        </div>
    );
}
export default Staff;