import { fetchStaff } from "@/app/lib/db";
import StaffList from "../Components/StaffList";
import SearchForm from "../Components/SearchForm";
export const metadata = {
  title: "Staff Information",
  description: "Generated by create next app",
};
const Staff = async () => {
  const staffData = await fetchStaff();

  return (
    <div className='container'>
      <h2>Staff List</h2>
      <SearchForm />
      <StaffList staffData={staffData} />
    </div>
  );
};
export default Staff;
